{"meaning": "Try and Except statement is used to handle these errors within our code in Python. The try block is used to check some code for errors i.e the code inside the try block will execute when there is no error in the program. Whereas the code inside the except block will execute whenever the program encounters some error in the preceding try block.", "syntax": "try:\n <body>\n raise Exception()\nexcept Exception as e:\n <exception handling>\nfinally:\n <clean-up>\n", "example": "def divide(x, y):\n    try:\n        # Floor Division : Gives only Fractional Part as Answer\n        result = x // y\n        print(\"Yeah ! Your answer is :\", result)\n    except ZeroDivisionError:\n        print(\"Sorry ! You are dividing by zero \")\ndivide(3, 2)"}